version: "3"

services:
  selenium-hub:
    image: selenium/hub:latest  # Use the stable version instead of a date-specific version
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest # Use the stable version
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    volumes:
      - /dev/shm:/dev/shm
